### ISSUE TITLE
[Feature Request]: Create a Checkout Page

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#41]
### Is your feature request related to a problem? Please describe.

Currently we don't have any checkout page.

### Describe the solution you'd like

Create the checkout page according to the below design:

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/e20a1d10-1d4b-4553-8954-4fc5a6604a60)

### Developer Help

You should follow these milestones in order to solve this issue:

- [ ] Since many UI elements are taken from Bus Details Drawer, so you have to convert few elements to components from drawer and use it here.
- [ ] Create the checkout page design
- [ ] Make the page responsive

**Comment by NightFury742** [comment]
@prajjwalkapoor I want to work on this issue, please assign it to me. I will keep in mind the listed milestones while creating the component. I will also pass in props for various details in the page as and when needed.

**Comment by prajjwalkapoor** [comment]
@NightFury742 Sure, You can work on this. State has to be manage globally with `zustand` here. @Bhavik-ag is also working on the same. Just coordinate with him to get the idea of how to manage state.

**Comment by NightFury742** [comment]
Alright  👍

**Comment by parthksingh1** [comment]
@prajjwalkapoor  I want to work on this issue, please assign it to me.

**Comment by parthksingh1** [comment]
Sir I would like to be unassigned from checkout issue as I am currently facing several obstacles that prevent me from effectively working on it. Firstly, there is a merging problem due to my usage of Windows, which creates difficulties in the process. and also I have encountered various challenges related to the WSL Docker installation on my Windows system.
I have discussed these issues with Eshaan he will further proceed the work, I apologize for any inconvenience caused.
